name: cheme
channels:
        - defaults
        - conda-forge
dependencies:
        - python=3.7.2
        - jupyterlab
        - ipython=7.3.0
        - ipython_genutils=0.2.0
        - jupyter=1.0.0
        - jupyter_client=5.2.4
        - numpy=1.16.2
        - scipy=1.2.1
        - pandas=0.24.2
        - matplotlib
        - seaborn
